{{- if .Values.readyKafka.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dl-poc.fullname" . }}-ready-zookeeper
  namespace: {{ include "dl-poc.readyKafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dl-poc.fullname" . }}-ready-zookeeper
  replicas: {{ .Values.readyZookeeper.replicas }}
  selector:
    matchLabels:
      {{- include "dl-poc.selectorLabels" . | nindent 6 }}
      app: ready-zookeeper
  template:
    metadata:
      labels:
        {{- include "dl-poc.selectorLabels" . | nindent 8 }}
        app: ready-zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ready-zookeeper
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: zookeeper
          image: {{ .Values.readyZookeeper.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: client
          resources:
            {{- toYaml .Values.readyZookeeper.resources | nindent 12 }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-log
              mountPath: /var/lib/zookeeper/log
      volumes:
        - name: zookeeper-log
          emptyDir: {}
      {{- with .Values.readyZookeeper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readyZookeeper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.readyZookeeper.persistence.size }}
        {{- if .Values.readyZookeeper.persistence.storageClassName }}
        storageClassName: {{ .Values.readyZookeeper.persistence.storageClassName }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dl-poc.fullname" . }}-ready-zookeeper
  namespace: {{ include "dl-poc.readyKafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    {{- include "dl-poc.selectorLabels" . | nindent 4 }}
    app: ready-zookeeper
{{- end -}}
