{{- if .Values.readyKafka.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dl-poc.fullname" . }}-ready-kafka
  namespace: {{ include "dl-poc.readyKafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "dl-poc.fullname" . }}-ready-kafka
  replicas: {{ .Values.readyKafka.replicas }}
  selector:
    matchLabels:
      {{- include "dl-poc.selectorLabels" . | nindent 6 }}
      app: ready-kafka
  template:
    metadata:
      labels:
        {{- include "dl-poc.selectorLabels" . | nindent 8 }}
        app: ready-kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ready-kafka
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kafka
          image: {{ .Values.readyKafka.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: hostport
            - containerPort: 29092
              name: clusterport
          resources:
            {{- toYaml .Values.readyKafka.resources | nindent 12 }}
          env:
            - name: KAFKA_BROKER_ID
              value: "-1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ include "dl-poc.fullname" . }}-ready-zookeeper.{{ include "dl-poc.readyKafkaNamespace" . }}.svc.cluster.local:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "dl-poc.fullname" . }}-ready-kafka.{{ include "dl-poc.readyKafkaNamespace" . }}.svc.cluster.local:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      {{- with .Values.readyKafka.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readyKafka.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.readyKafka.persistence.size }}
        {{- if .Values.readyKafka.persistence.storageClassName }}
        storageClassName: {{ .Values.readyKafka.persistence.storageClassName }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dl-poc.fullname" . }}-ready-kafka
  namespace: {{ include "dl-poc.readyKafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      name: hostport
    - port: 29092
      targetPort: 29092
      name: clusterport
  selector:
    {{- include "dl-poc.selectorLabels" . | nindent 4 }}
    app: ready-kafka
{{- end -}}
