apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dl-poc.fullname" . }}-spark-service-account
  namespace: {{ include "dl-poc.sparkMailIngestNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dl-poc.fullname" . }}-spark-role
  namespace: {{ include "dl-poc.sparkMailIngestNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dl-poc.fullname" . }}-spark-rolebinding
  namespace: {{ include "dl-poc.sparkMailIngestNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "dl-poc.fullname" . }}-spark-service-account
    namespace: {{ include "dl-poc.sparkMailIngestNamespace" . }}
roleRef:
  kind: Role
  name: {{ include "dl-poc.fullname" . }}-spark-role
  apiGroup: rbac.authorization.k8s.io
