apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dl-poc.fullname" . }}-spark-dlq-processor
  namespace: {{ include "dl-poc.sparkDlqProcessorNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sparkDlqProcessor.replicas }}
  selector:
    matchLabels:
      {{- include "dl-poc.selectorLabels" . | nindent 6 }}
      app: spark-dlq-processor
  template:
    metadata:
      labels:
        {{- include "dl-poc.selectorLabels" . | nindent 8 }}
        app: spark-dlq-processor
    spec:
      {{- with .Values.sparkDlqProcessor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sparkDlqProcessor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spark-dlq-processor
          image: {{ .Values.sparkDlqProcessor.image }}
          imagePullPolicy: IfNotPresent
          command: ["python3", "apps/spark/spark_dlq_processor.py"]
          resources:
            {{- toYaml .Values.sparkDlqProcessor.resources | nindent 12 }}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ include "dl-poc.kafkaBootstrap" . | quote }}
            - name: KAFKA_DLQ_TOPIC
              value: {{ .Values.sparkDlqProcessor.kafkaDlqTopic | quote }}
