{{- if .Values.kafka.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dl-poc.fullname" . }}-zookeeper-pvc
  namespace: {{ include "dl-poc.kafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size }}
  {{- if .Values.zookeeper.persistence.storageClassName }}
  storageClassName: {{ .Values.zookeeper.persistence.storageClassName }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dl-poc.fullname" . }}-zookeeper
  namespace: {{ include "dl-poc.kafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dl-poc.selectorLabels" . | nindent 6 }}
      app: zookeeper
  template:
    metadata:
      labels:
        {{- include "dl-poc.selectorLabels" . | nindent 8 }}
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-log
              mountPath: /var/lib/zookeeper/log
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: {{ include "dl-poc.fullname" . }}-zookeeper-pvc
        - name: zookeeper-log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dl-poc.fullname" . }}-zookeeper
  namespace: {{ include "dl-poc.kafkaNamespace" . }}
  labels:
    {{- include "dl-poc.labels" . | nindent 4 }}
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    {{- include "dl-poc.selectorLabels" . | nindent 4 }}
    app: zookeeper
{{- end -}}
